### ISSUE TITLE
Don't generate new Access token when used with `fallbackToLastPlayed`

### ISSUE THREAD

**Issue by rocktimsaikia** [rocktimsaikia/spotify-mini#10]
https://github.com/rocktimsaikia/spotify-mini/blob/50bc8ec3a309aabe56adb079d7740a14c7a62702/index.ts#L72
Use the same access token in `getLastPlayed()` generated by currently playing API call when there is no ongoing track. It does not make sense to regenerate a new token instead of using the existing one

**Comment by melosh101** [comment]
wouldnt it be ideal to add the access token to the class as a private property and refetch it when it expires since they expire after an hour? . would spare a couple of requests

**Comment by rocktimsaikia** [comment]
Yes. That should be the ideal implementation. PRs are open for this!
It should ideally only generate access token once the api throws an expired accesstoken error which is probably `401` if I am not wrong
