### ISSUE TITLE
set up a pre-commit hook

### ISSUE THREAD

**Issue by rocktimsaikia** [rocktimsaikia/spotify-mini#2]
Set up a pre-commit hook for tests.

Resource: https://github.com/typicode/husky

**Comment by fuadop** [comment]
Hey @rocktimsaikia 👋🏾 , 

Can I work on this ? It's just to setup husky right ?

**Comment by rocktimsaikia** [comment]
@fuadop Sure. Yes.

**Comment by fuadop** [comment]
Hey @rocktimsaikia , can you review ?
