### ISSUE TITLE
Add `limit` option to `getLastPlayed` method to get the n number of last played tracks

### ISSUE THREAD

**Issue by rocktimsaikia** [rocktimsaikia/spotify-mini#7]
Currently, the default limit is 1 which is fine. But there should be a `limit` option to get the n number of last played tracks
https://developer.spotify.com/console/get-recently-played/

**Comment by fuadop** [comment]
Can I take this on @rocktimsaikia ? 🤔 ..

Also I cant find refresh token on my spotify dashboard.

**Comment by rocktimsaikia** [comment]
Refresh token needs to be generated manually. You can take look around the web for this.
The process can be quite tedious, I might work on a new CLI tool to automate this process.

**Comment by fuadop** [comment]
oh.. I see.. Let me check around the web then . Thanks @rocktimsaikia
